knp_menu:
  twig:
    template: knp_menu.html.twig

parameters:
  knp_menu.renderer.twig.options:
    currentClass: current-menu-item

services:
  app.knp.main_menu:
    class: Knp\Menu\MenuItem
    factory: ['@App\Menu\MainMenu', createMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: main_menu }
  app.knp.admin_menu:
    class: Knp\Menu\MenuItem
    factory: ['@App\Menu\AdminMenu', createMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: admin_menu }

